# Generated by Django 4.2.4 on 2023-08-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_day',
            field=models.EmailField(default='2000-00-00', max_length=254),
        ),
    ]
