# Generated by Django 4.2.4 on 2023-08-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_day',
            field=models.DateField(default='2000-00-00'),
        ),
    ]
