# Generated by Django 4.2.4 on 2023-08-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_birth_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_day',
        ),
    ]
