# Generated by Django 4.2.4 on 2023-08-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_day',
            field=models.DateField(blank=None, max_length=50, null=None),
        ),
    ]
