# Generated by Django 4.2.4 on 2023-08-29 15:30

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customuser_birth_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_day',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=None, default='2000-01-01', max_length=50, null=None, validators=[users.validators.validate_age]),
            preserve_default=False,
        ),
    ]
