# Generated by Django 4.2.4 on 2023-09-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_customuser_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ref',
            field=models.CharField(blank=None, default=31, max_length=12, null=None),
            preserve_default=False,
        ),
    ]
